name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
  runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      
      name: Deploy to server
      run: 
        ssh user@server "cd /${{ github.event.repository.name }} && git pull && make build backend && make up-all"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}