name: Test Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Check secrets availability
        run: |
          echo "Checking if secrets are available..."
          if [ -z "${{ secrets.SSH_USER }}" ]; then echo "SSH_USER is not set"; fi
          if [ -z "${{ secrets.SSH_HOST }}" ]; then echo "SSH_HOST is not set"; fi
          if [ -z "${{ secrets.PAT }}" ]; then echo "PAT is not set"; fi
          echo "SSH_PRIVATE_KEY: [hidden for security reasons]"
          
      - name: Display Secrets
        run: |
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "PAT: ${{ secrets.PAT }}"
          echo "SSH_PRIVATE_KEY: [hidden for security reasons]"


    
